name = "openai-cloudflare"
main = "worker.js"
compatibility_date = "2024-06-01"
workers_dev = false

account_id = "${CF_ACCOUNT_ID}"
route = "${CF_ROUTE}"

[vars]
OPENAI_API_KEY = "${OPENAI_API_KEY}"
ACCESS_TOKEN = "${ACCESS_TOKEN}"

