compatibility_flags = ["nodejs_compat"]

compatibility_date = "2024-06-01"
main = "worker.js"
name = "openai-cloudflare"
workers_dev = false
modules = false  # ⬅️ обязательный параметр

account_id = "${CF_ACCOUNT_ID}"
zone_id = "${CF_ZONE_ID}"
route = "${CF_ROUTE}"

[vars]
OPENAI_API_KEY = "${OPENAI_API_KEY}"
ACCESS_TOKEN = "${ACCESS_TOKEN}"
